// Mocks generated by Mockito 5.4.6 from annotations
// in send_money/test/features/send_money/presentation/cubits/send_money_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money/features/send_money/domain/entities/send_money_entity.dart'
    as _i2;
import 'package:send_money/features/send_money/domain/services/send_money_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSendMoneyEntity_0 extends _i1.SmartFake
    implements _i2.SendMoneyEntity {
  _FakeSendMoneyEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendMoneyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMoneyService extends _i1.Mock implements _i3.SendMoneyService {
  @override
  _i4.Future<_i2.SendMoneyEntity> sendMoney(
    int? accountNumber,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMoney, [accountNumber, amount]),
            returnValue: _i4.Future<_i2.SendMoneyEntity>.value(
              _FakeSendMoneyEntity_0(
                this,
                Invocation.method(#sendMoney, [accountNumber, amount]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SendMoneyEntity>.value(
              _FakeSendMoneyEntity_0(
                this,
                Invocation.method(#sendMoney, [accountNumber, amount]),
              ),
            ),
          )
          as _i4.Future<_i2.SendMoneyEntity>);
}
