// Mocks generated by Mockito 5.4.6 from annotations
// in send_money/test/features/dashboard/presentation/cubits/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money/core/cache/wallet_cache_service.dart' as _i6;
import 'package:send_money/core/storage/secure_storage_service.dart' as _i5;
import 'package:send_money/features/dashboard/domain/entities/wallet_entity.dart'
    as _i2;
import 'package:send_money/features/dashboard/domain/services/dashboard_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWalletEntity_0 extends _i1.SmartFake implements _i2.WalletEntity {
  _FakeWalletEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardService extends _i1.Mock implements _i3.DashboardService {
  @override
  _i4.Future<_i2.WalletEntity> getWalletData() =>
      (super.noSuchMethod(
            Invocation.method(#getWalletData, []),
            returnValue: _i4.Future<_i2.WalletEntity>.value(
              _FakeWalletEntity_0(this, Invocation.method(#getWalletData, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.WalletEntity>.value(
              _FakeWalletEntity_0(this, Invocation.method(#getWalletData, [])),
            ),
          )
          as _i4.Future<_i2.WalletEntity>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i5.SecureStorageService {
  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [WalletCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletCacheService extends _i1.Mock
    implements _i6.WalletCacheService {
  @override
  _i4.Future<void> saveWallet(_i2.WalletEntity? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#saveWallet, [wallet]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
